### ISSUE TITLE
Ошибка запуска теста?

### ISSUE THREAD

**Issue by y0f0** [vanerk03/SkakovLabO4ka#13]
https://github.com/vanerk03/SkakovLabO4ka/blob/1e5e93e9f8ee55f83a90e2cc00d0abb89f07d34b/collect.py#L142

Мне кажется тут ошибка в collect.py, так как этот сall вызывает"python main.exe input.txt output.txt" очевидно неправильный запуск теста

**Comment by vanerk03** [comment]
Да, тут реально косяк, забыли убрать при дебаге
