### ISSUE TITLE
sm fixs

### ISSUE THREAD

**Issue by Nikkirche** [vanerk03/SkakovLabO4ka#17]
Какой .exe  на линуксе/маке?
![image](https://user-images.githubusercontent.com/49571700/164986041-dd224680-165b-4c8f-a21b-5ad47d610281.png)
И в <i>generate.py<i/> имеет наверное смысл убрать указание папки, должно получится +- так
`with Path(os.getcwd()).joinpath("words.json").open("r") as file:
    WORD_LIST = json.load(file)
`

**Comment by PhoenixNazarov** [comment]
fixed 👍
