### ISSUE TITLE
Развитие веток

### ISSUE THREAD

**Issue by PhoenixNazarov** [vanerk03/SkakovLabO4ka#26]
Ветки:
+ master - updater с `git checkout`, переносящий на ветку с актуальной версией hw*. И с общим описанием репозитория
+ dev - работа над текущей версией hw
+ dev, hw* - в будущем не должны содержать `git checkout`

Актуальные версии переносить через `pull request` dev -> hw*

**Comment by PhoenixNazarov** [comment]
Реализовано. В процессе тестирования

**Comment by vanerk03** [comment]
Done
